### ISSUE TITLE
Project Form: Add multi select drop down for 'Looking for' - contributor type (PM, Front end.....)

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#100]
#92 

**User story:** As a user, it is helpful to know the level of contributors project lead is seeking

**Deliverables**:
Add multi-select for contributor type, users should be allowed to input multiple values of their own contributor types.
E.G:
- Front end Engineer
- Product Managers
- Backend Engineers
- UX researcher

**Instructions:** To implement `Looking For` field use https://react-select.com/creatable same as in “Creatable Multiselect Example”.

**Mockup**
<img width="544" alt="Screen Shot 2020-09-27 at 5 46 48 pm" src="https://user-images.githubusercontent.com/3733773/94380226-88f3ef80-00e9-11eb-94a0-d7f266474a24.png">

Higher definition PDF file: 
[She's_Coding_Projects.pdf](https://github.com/shescoding/projects-platform-frontend/files/5289260/She.s_Coding_Projects.pdf)

**Comment by nadyafebi** [comment]
Hi! Would love to work on this

**Comment by AnanjayaTyagi** [comment]
Looking forward to working on it!

**Comment by nurmerey** [comment]
> Looking forward to working on it!

Hi @AnanjayaTyagi Sorry for the mixup, it looks like this task has already been addressed in #151 . I will go ahead and find you a different task to work on!

**Comment by AnanjayaTyagi** [comment]
Okay, no problem!

Best,
Ananjaya

-----
Ananjaya Tyagi
Duke University | The Graduate School
MS in Electrical and Computer Engineering
Class of 2021
LinkedIn<https://www.linkedin.com/in/ananjaya-tyagi/>
(she/her)
