### ISSUE TITLE
Project Card: Create API to delete project

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#103]
Related to #115 and #116. Recommend to work together on all three.

**User story:** As a user, I would like to ability to delete my project

**Deliverable:**
Create API endpoint that would delete a project

Ask @Leyi-Li or @nurmerey for help!

**Comment by natalie-poulson** [comment]
Commenting to get assigned

**Comment by nurmerey** [comment]
@natalie-poulson path to file - /projects-platform-frontend/server/routes/github_oauth.js

**Comment by nurmerey** [comment]
The issue is done in #144 PR.
