### ISSUE TITLE
Homepage: Remove 'Sign in with Github' under the 'Open Source Collab......' section

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#108]
**user story**: As a user, it is not necessary to have two ' Sign in with Github' buttons on the homepage.

**Deliverable**
Rename the 'Sign in with Github' button below the 'Open Source Collab...' section to "Join Us"

![Screen Shot 2020-09-24 at 9 10 34 pm](https://user-images.githubusercontent.com/3733773/94225762-c7e83200-feaa-11ea-84f1-cc398d30b0ca.png)

**Comment by skodamarthi** [comment]
Can I work on this?
