### ISSUE TITLE
Project Form: Add multi select drop down for Tech Stack

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#112]
Related to #118 #117 

**User story:** As a user, I would like to be able to consistently see the tech stack used on each project.

**Deliverable:**
Add multi-select for tech stack, users should be allowed to input multiple values of their own tech

**Instructions:** To implement Tech Stack field use https://react-select.com/creatable same as in “Creatable Multiselect Example”.

**Mockup**
<img width="552" alt="Screen Shot 2020-09-27 at 5 08 06 pm" src="https://user-images.githubusercontent.com/3733773/94379339-788d4600-00e4-11eb-8c94-d9855ddd67fe.png">

Higher definition PDF file: 
[She's_Coding_Projects.pdf](https://github.com/shescoding/projects-platform-frontend/files/5289260/She.s_Coding_Projects.pdf)

**Comment by sushmukund26** [comment]
Working on this issue

**Comment by nurmerey** [comment]
Addressed by #147 and #149!
