### ISSUE TITLE
Create a page to add a project 

### ISSUE THREAD

**Issue by nurmerey** [shescoding/projects-platform-frontend#23]
Part of EPIC #19 
- [x] Follow the below sketch to create the UI
- [ ] ~~Input validation for non empty field~~ https://github.com/shescoding/projects-platform-frontend/issues/29

![Image from iOS (1)](https://user-images.githubusercontent.com/3733773/70469837-b00c0280-1a7e-11ea-9eda-0f3dbce1b014.jpg)

**Comment by partiallymisplaced** [comment]
This has been done in #28
