### ISSUE TITLE
Create Sign in / Welcome page

### ISSUE THREAD

**Issue by nurmerey** [shescoding/projects-platform-frontend#4]
PR: #11 
#4 
- [x] Placeholder messaging text 
- [x] Layout
- [x] Button to sign in with Github

![03-screenshot-welcome](https://user-images.githubusercontent.com/1844100/68627555-e2800b00-0492-11ea-8fe6-e3cbf80251cf.png)

**Comment by partiallymisplaced** [comment]
Screenshots: 
![01-screenshot-sign-in](https://user-images.githubusercontent.com/1844100/68611072-18f75f00-046e-11ea-8d72-b64d870d0cf1.png)
![02-screenshot-sign-out](https://user-images.githubusercontent.com/1844100/68611078-1b59b900-046e-11ea-953e-4f28b266dbfc.png)

**Comment by nurmerey** [comment]
This is already completed in #11 by @partiallymisplaced
