### ISSUE TITLE
Project Card: Add description headers

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#91]
**User story:**
As a user, I would like to see headers for different sections within the project card. 

**Deliverables:**
1. Add section headers for 'Project Description' and 'Project Lead' as per the mockup.
2. Move 'Project Description' section to the top as per the mockup.

<img width="441" alt="Screen Shot 2020-09-27 at 4 42 46 pm" src="https://user-images.githubusercontent.com/3733773/94378741-ad979980-00e0-11eb-88d4-fe25f79f4186.png">

Higher definition PDF file: 
[She's_Coding_Projects.pdf](https://github.com/shescoding/projects-platform-frontend/files/5289260/She.s_Coding_Projects.pdf)

**Comment by innovation16** [comment]
How can we assign issues to ourselves?
