### ISSUE TITLE
Add Project Form: change label text

### ISSUE THREAD

**Issue by nurmerey** [shescoding/projects-platform-frontend#92]
#100 
**User Story:**
As a user, I would like to see more description on the 'Looking for:' section as it is unclear based on the current language.

**Deliverable:**
On "Add Project" page, change the label for the 'Looking For' input field to say: 
`Select or enter what type of contributors you're looking for`
<img width="525" alt="Screen Shot 2020-09-27 at 6 25 48 pm" src="https://user-images.githubusercontent.com/3733773/94381662-fce4c680-00ee-11eb-99d6-a533c1a0ff9d.png">

**Comment by FrozenGirl-spd** [comment]
Can i work on the issue @nurmerey ...

**Comment by nurmerey** [comment]
Hi @FrozenGirl-spd this issue is reserved for Grace Hopper Conference Open Source day.

**Comment by PriyankaHarish** [comment]
@nurmerey Can I work on this issue? :)
I'm a part of Open Source Day - GHC 2020.

**Comment by TabithaKavyu** [comment]
Gotcha
