### ISSUE TITLE
Project Form: Change select values for the Experience level

### ISSUE THREAD

**Issue by ctran14** [shescoding/projects-platform-frontend#98]
**User story:** As a user, the experience level is subjective, years of experience is sufficient

**Deliverables**
Update the select value to just show years of experience.

e.g:
0-1 years
1-3 years
3-5 years
5+ years
<img width="733" alt="Screen Shot 2020-09-15 at 4 18 02 PM" src="https://user-images.githubusercontent.com/64050970/93274374-155bf500-f76f-11ea-9d68-a9ebfef94419.png">

**Comment by jngong** [comment]
Thanks for assigning this to me. I will start to work on it 👍
